### ISSUE TITLE
EMP connector stops receiving notifications after an hour or so.

### ISSUE THREAD

**Issue by sourabhrajput** [forcedotcom/EMP-Connector#4]
I was performing some tests on my POC code and found that after sometime ( 1- 2 hours) notifications are not getting received, I waited for sometime assuming they might take time in some case and left it for another 1 hour but no notification I then restarted my program and pending notification got received, this happened all the time We performed test so I am logging issue for investigation

**Comment by sourabhrajput** [comment]
same question added in stackoverflow
http://stackoverflow.com/questions/42432553/sales-force-emp-connector-stops-receiving-notification-after-some-time

**Comment by avallfox** [comment]
Could you enhance the implementation (with reconnection) when connection is lost ?

**Comment by sfdc-hhildebrand** [comment]
This PR has the reconnect: https://github.com/forcedotcom/EMP-Connector/pull/6

However, it still does not handle 503's.

**Comment by avallfox** [comment]
We have tested the implementation (including the reconnection) and the problem is the same, yet (after 1-2 hours the channel is not receiving messages and it is impossible to reconnect) . It is impossible to detect the nature of the problem. We are using the Streaming API to listen "Salesforce Cases" from Java API and send them to Mobile Clients (IOS / Android).

**Comment by sfdc-hhildebrand** [comment]
Did you turn on debug logging?  It would be helpful if you could supply some more data regarding this, as I cannot debug this without something.

There's a lot of helpful logging and it would really help diagnose what is going on with your particular use case.

**Comment by avallfox** [comment]
Now i go to Sleep (Europe) but in a few hours i help you because i have added a lot of Logs ...

**Comment by wesleysee** [comment]
i'm having the same issues with the project that I'm working on, although I'm not sure if the root cause is the same as the reporter's. In my case, the streaming breaks because the login session expired. Hence handshaking again won't work, as it's still using the old credentials and bearer token.

Here are some logs with debug turned on.

```
2017-04-05 17:48:21.670 DEBUG 1 --- [t@1969969319-27] c.s.emp.connector.EmpConnector$1 : Received messages [{advice={reconnect=handshake, interval=0}, channel=/meta/connect, id=667, error=403::Unknown client, successful=false}]
2017-04-05 17:48:21.670 DEBUG 1 --- [t@1969969319-27] c.s.e.connector.EmpConnector$2.7c551ad4 : Processing {advice={reconnect=handshake, interval=0}, channel=/meta/connect, id=667, error=403::Unknown client, successful=false}
2017-04-05 17:48:21.671 INFO 1 --- [t@1969969319-27] c.salesforce.emp.connector.EmpConnector : error in connect: 403::Unknown client
2017-04-05 17:48:21.671 DEBUG 1 --- [t@1969969319-27] c.s.e.connector.EmpConnector$2.7c551ad4 : Transport failure: FailureInfo@232303d1[transport=com.salesforce.emp.connector.EmpConnector$1@68fe48d7,cause=null,action=handshake] for {advice={reconnect=handshake, interval=0}, channel=/meta/connect, id=667, error=403::Unknown client, successful=false}
2017-04-05 17:48:21.671 DEBUG 1 --- [t@1969969319-27] c.s.e.connector.EmpConnector$2.7c551ad4 : Transport failure handling: FailureInfo@232303d1[transport=com.salesforce.emp.connector.EmpConnector$1@68fe48d7,cause=null,action=handshake]
2017-04-05 17:48:21.672 DEBUG 1 --- [t@1969969319-27] c.s.e.connector.EmpConnector$2.7c551ad4 : Scheduled handshake in 0+0 ms
2017-04-05 17:48:21.672 DEBUG 1 --- [t@1969969319-27] c.s.e.connector.EmpConnector$2.7c551ad4 : State updated: CONNECTED -> REHANDSHAKING
2017-04-05 17:48:21.673 DEBUG 1 --- [t@1969969319-27] c.s.e.connector.EmpConnector$2.7c551ad4 : Notifying threads in waitFor()
2017-04-05 17:48:21.673 DEBUG 1 --- [pool-4-thread-1] c.s.e.connector.EmpConnector$2.7c551ad4 : Handshaking on transport com.salesforce.emp.connector.EmpConnector$1@68fe48d7: {supportedConnectionTypes=[long-polling], channel=/meta/handshake, id=668, version=1.0}
2017-04-05 17:48:21.673 DEBUG 1 --- [pool-4-thread-1] c.s.e.connector.EmpConnector$2.7c551ad4 : Sending messages [{ext={replay=true}, clientId=9bkcuh053llw7olet0x9rdr8eb, supportedConnectionTypes=[long-polling], channel=/meta/handshake, id=668, version=1.0}]
2017-04-05 17:48:21.758 DEBUG 1 --- [t@1969969319-29] c.s.emp.connector.EmpConnector$1 : Received messages [{ext={replay=true}, advice={reconnect=none}, channel=/meta/handshake, id=668, error=401::Authentication invalid, successful=false}]
2017-04-05 17:48:21.758 DEBUG 1 --- [t@1969969319-29] c.s.e.connector.EmpConnector$2.7c551ad4 : Processing {ext={replay=true}, advice={reconnect=none}, channel=/meta/handshake, id=668, error=401::Authentication invalid, successful=false}
2017-04-05 17:48:21.758 INFO 1 --- [t@1969969319-29] c.salesforce.emp.connector.EmpConnector : received handshake response: java.util.concurrent.CompletableFuture@52ce5921[Completed normally]
2017-04-05 17:48:21.758 INFO 1 --- [t@1969969319-29] c.salesforce.emp.connector.EmpConnector : error in handshake: 401::Authentication invalid
2017-04-05 17:48:21.758 DEBUG 1 --- [t@1969969319-29] c.s.e.connector.EmpConnector$2.7c551ad4 : Transport failure: FailureInfo@7bd49dc5[transport=com.salesforce.emp.connector.EmpConnector$1@68fe48d7,cause=null,action=none] for {ext={replay=true}, advice={reconnect=none}, channel=/meta/handshake, id=668, error=401::Authentication invalid, successful=false}
2017-04-05 17:48:21.759 DEBUG 1 --- [t@1969969319-29] c.s.e.connector.EmpConnector$2.7c551ad4 : Transport failure handling: FailureInfo@7bd49dc5[transport=com.salesforce.emp.connector.EmpConnector$1@68fe48d7,cause=null,action=none]
2017-04-05 17:48:21.759 DEBUG 1 --- [t@1969969319-29] c.s.e.connector.EmpConnector$2.7c551ad4 : State updated: REHANDSHAKING -> TERMINATING
2017-04-05 17:48:21.759 DEBUG 1 --- [t@1969969319-29] c.s.e.connector.EmpConnector$2.7c551ad4 : State updated: TERMINATING -> DISCONNECTED
2017-04-05 17:48:21.759 DEBUG 1 --- [t@1969969319-29] c.s.e.connector.EmpConnector$2.7c551ad4 : Notifying threads in waitFor()
```

Based on the above, what seems to be happening is:
1. Salesforce returned `403::Unknown client` in the CONNECT channel.
2. CometD client library tries to do a handshake again.
3. Since authentication token have not changed, and it has already expired, Salesforce returned `401::Authentication invalid`
4. CometD client terminates and disconnects due to the failure.

I think what is needed to fix this is:
* Detect when session has expired. Detecting the `403::Unknown client` error could be one way to do this, although I'm not sure if this is the best way.
* Provide ability to refresh the authentication token. Then when the above error is detected, we can trigger the token refresh, such that the handshake done by the CometD library will pass.

**Comment by sfdc-hhildebrand** [comment]
Excellent.  Thank you for this.  We have just released a fix for this, so please retry and let me know the result.  The issue is that when the routing cookie expired, we would not return reconnect advice to the client.  This has been fixed and should be live in all instances.

**Comment by wesleysee** [comment]
Can you clarify on when we expect to encounter the reconnect advice? Is routing cookie the same as the authentication (bearer) token?

I've actually implemented my own `EmpConnector` that performs the re-authentication during rehandshake, and it's been working fine for a day so far.

**Comment by sfdc-hhildebrand** [comment]
The routing cookie is a cookie placed on the connection by the F5, the first time it sees the connection to /cometd/*.  This cookie is controlled by the F5 and is not an authorization cookie.  This cookie also has a time limit and will expire eventually.  When it does, the F5 will reroute the connection, placing setting a new value of the cookie.  When the connection is rerouted, the client is on a new app server that did not previously host the bayeux session.  Thus, the client receives the 403 with reconnect advice.

If you auth header is still valid, there should be no need to reauthorize.  If this is working, I believe it just means that you're essentially doing the equivalent of a new handshake, which provides the same functionality.  If you can try this without your fix, that would be useful.

**Comment by wesleysee** [comment]
thanks for the explanation. I'm still seeing the same behavior as before though, so I'm not sure if the situation you're describing is what I'm encountering. When the `403::Unknown client` error is encountered, `reconnect=handshake` advice is indicated, but rehandshaking fails because my authentication token has expired. 

As an additional note, I'm consistently seeing this `403` error every 3 hours.

Note that I tried this on the `resubscribe-on-disconnect` branch, but I assume the behavior will be the same on the `master` branch.

**Comment by sfdc-hhildebrand** [comment]
Well, if your token expires every three hours, you'll have to update it.  Fixing the advice not returned on 403::UnknownClient problem with the F5 is unfortunately not going to fix that.

I'm closing this, as the F5 problem is fixed and dealing with reauthentication is another thing entirely.

**Comment by mrkam2** [comment]
How about reporting back that the connection was terminated?

**Comment by rmadireddy** [comment]
I am seeing same issue. I am using "resubscribe-on-disconnect branch" and looks like its not related to authorization. #15
